stages:
  data_ingestion:
    cmd: python -m src.data_ingestion
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
    params:
    - data_ingestion.test_size
    - data_ingestion.random_state
  data_preprocessing:
    cmd: python -m src.data_preprocessing
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed_data
  feature_engineering:
    cmd: python -m src.feature_engineering
    deps:
    - data/processed_data
    - src/feature_engineering.py
    outs:
    - data/transformed
    params:
    - feature_engineering.max_features
  model_training:
    cmd: python -m src.model_training
    deps:
    - data/transformed
    - src/model_training.py
    outs:
    - models/rf_model.pkl
    params:
    - model_training.n_estimators
    - model_training.random_state
  model_evaluation:
    cmd: python -m src.model_evaluation
    deps:
    - models/rf_model.pkl
    - data/transformed
    - src/model_evaluation.py

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
